version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8090:8090"
    restart: unless-stopped
    depends_on: 
      - kafka
  retry:
    build:
      context: .
      dockerfile: Dockerfile.retry
    restart: unless-stopped
    depends_on: 
      - kafka
